gg.jte.development-mode=true
spring.application.name=chesstools
spring.datasource.url=jdbc:postgresql://localhost:5432/chesstools
spring.datasource.username=ppeter777
spring.datasource.password=henke115
spring.jpa.hibernate.ddl-auto=validate